config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
    resources :lists, only: [:new, :create, :index, :show] do
        resources :bookmarks, only: [:new, :create, :destroy]
      end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :movie
    belongs_to :list
    validates :list, presence: true
    validates :movie, presence: true
    validates_length_of :comment, :minimum => 6
    validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks,  dependent: :destroy
    has_many :movies, through: :bookmarks
    validates :name, presence: true
    validates_uniqueness_of :name 
    has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    validates :overview, presence: true
    validates :title, presence: true
    validates_uniqueness_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    def new 
        @list = List.find(params[:list_id])
        @bookmark = Bookmark.new
    end 
    def destroy
      @bookmark.destroy
    end 
    def create
        @list = List.find(params[:list_id])
        @bookmark = Bookmark.new(bookmark_params)
        @bookmark.list = @list
        if @bookmark.save
          redirect_to list_path(@list)
        else
          render :new
        end
    end

    private 
    def bookmark_params
        params.require(:bookmark).permit(:comment, :movie_id)
    end 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def new
        @list = List.new
    end 
    def index
        @lists = List.all
    end 
    def show
        @list = List.find(params[:id])
    end 
    def create
        @list = List.new(params.require(:list).permit(:name, :photo))
        @list.save
        if @list.save
          redirect_to list_path(@list)
        else
          render :new
        end
    end 
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, prompt: "Select a movie" %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New Boomark</h1>

<%= render "form", list: @list, bookmark: @bookmark %>

</br>
<%= link_to("Back to list", list_path(@list)) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name, placeholder: "Write the list name here" %>
  <%= f.input :photo, as: :file %>
  <div class="new-btn">
    <%= f.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  Your lists
</div>
<ul>
  <% @lists.each do |list| %>
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <p><%= link_to list.name, list_path(list), class: "btn btn-primary" %></p>
        </div>
      </div>
  <% end %>
</ul>
<div class="new-btn">
<%= link_to "Add a new list", new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <h1>New List</h1>
</div>

<%= render "form", list: @list %>

</br>
<div class="new-btn">
<%= link_to("Back to list", lists_path, class: "btn btn-primary") %>
</div>

app/views/lists/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <h2><%= @list.name %></h2>
</div>

<ul class="list-group">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-product">
      <img src="<%= bookmark.movie.poster_url%>" />
      <div class="card-product-infos">
        <li class="list-group-item"><%= bookmark.movie.title%></li>
        <li class="list-group-item"><%= bookmark.comment%></li>
        <li class="list-group-item"><%= bookmark.movie.overview%></li>
      </div>
    </div>
  <% end %>
</ul>

<%= link_to("Back to list", root_path, class: "btn btn-primary")  %>
<%= link_to("Add a bookmark", new_list_bookmark_path(@list), class: "btn btn-primary")  %>